# -*- coding: utf-8 -*-
"""DemoWork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HRSZHHEPrEH0uiJvTjWH9B7MmGCQC4eu
"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile our_application.py
# import streamlit as st
# st.title('Hello World')

!wget -q -O - ipv4.icanhazip.com

! streamlit run our_application.py & npx localtunnel --port 8501